{
    'name': 'Restaurant Task Manager',
    'version': '19.0.3.0.0',
    'category': 'Human Resources',
    'summary': 'Shift-based task checklists with photo proof and digital sign-off',
    'description': 'Simplified restaurant task management: checklists, photo proof, '
                   'digital signature sign-off, escalation, and attendance integration.',
    'author': 'Krawings',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'hr', 'hr_attendance', 'planning'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/mail_templates.xml',
        'data/cron_jobs.xml',
        'views/task_template_views.xml',
        'views/task_list_views.xml',
        'views/task_item_views.xml',
        'views/escalation_views.xml',
        'views/dashboard_views.xml',
        'views/planning_slot_views.xml',
        'views/attendance_views.xml',
        'views/menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'restaurant_task_manager/static/src/css/task_manager.css',
            'restaurant_task_manager/static/src/apps_home/apps_home.js',
            'restaurant_task_manager/static/src/apps_home/apps_home.xml',
        ],
    },
    'post_init_hook': '_set_apps_home_action',
    'installable': True,
    'application': True,
}
